### PR TITLE
Allow multiple letsencrypt clients.

### PR DESCRIPTION
**Pull request by mworrell**
These changes make it possible to have multiple LetsEncrypt clients running.
This is useful for systems with more than one hostname. 

We use this now on the master branch of Zotonic.

Fix problem with 'valid' cert requests.
Fix problem with SANs when openssl conf file is a on a non-standard path.

### CODE REVIEW

**Comment by gbour** [comment]
Hi @mworrell 
Thanks very much for your PR. I'll review it quickly

**Comment by mworrell** [comment]
I am checking right now why the build gives problems with the standalone tls test.

**Comment by mworrell** [comment]
@gbour Maybe you can help me, as I don't understand the logs.

I get a timeout waiting for the validation on the standalone tls test.

https://api.travis-ci.org/jobs/229135672/log.txt?deansi=true

```erlang
challenge(status, _, "/acme/challenge/s0osghS1QW7vbcwXT0Mv1DxzaAJ5DF6oMWZgep4R5Yo/2") => #{body => 
<<"{\n  \"type\": \"tls-sni-01\",\n  \"status\": \"pending\",\n  \"uri\": \"http://127.0.0.1:4000/acme/challenge/s0osghS1QW7vbcwXT0Mv1DxzaAJ5DF6oMWZgep4R5Yo/2\",\n  \"token\": \"_LA1uJT33G5EdW49uK5OwzWh5t_MFVJq59IVyQqJrTE\"\n}">>,
    headers => [{<<"boulder-request-id">>,
      <<"O6yiQWy8_MqdisGpZXG2edobktm07spqJqYLDam2FBU">>},
     {<<"cache-control">>,
      <<"public, max-age=0, no-cache">>},
     {<<"content-type">>,
      <<"application/json">>},
     {<<"link">>,
      <<";rel=\"up\"">>},
     {<<"location">>,
      <<"http://127.0.0.1:4000/acme/challenge/s0osghS1QW7vbcwXT0Mv1DxzaAJ5DF6oMWZgep4R5Yo/2">>},
     {<<"replay-nonce">>,
      <<"kcU38CS7pGOdNOMG45mQUyjNMlimqBBswUd64rkRSn8">>},
     {<<"date">>,
      <<"Fri, 05 May 2017 14:09:29 GMT">>},
     {<<"content-length">>,
      <<"202">>}],
    status_code => 202}
```

But at the end of the log I see `valid` for this nonce:

```json
{"ID":"O6yiQWy8_MqdisGpZXG2edobktm07spqJqYLDam2FBU",
"ClientAddr":"172.17.0.1:57174",
"Endpoint":"/acme/challenge/s0osghS1QW7vbcwXT0Mv1DxzaAJ5DF6oMWZgep4R5Yo/2",
"Method":"GET","Errors":null,
"ResponseNonce":"kcU38CS7pGOdNOMG45mQUyjNMlimqBBswUd64rkRSn8",
"Extra":{
"AuthorizationExpires":"2017-07-04T14:08:52Z",
"AuthorizationID":"s0osghS1QW7vbcwXT0Mv1DxzaAJ5DF6oMWZgep4R5Yo",
"AuthorizationIdentifier":{
    "type":"dns","value":"le.wtf"
},
"AuthorizationRegistrationID":1,
"AuthorizationStatus":"valid",
"ChallengeID":2,
"ChallengeType":"tls-sni-01"
},
"Code":0}
```

**Comment by mworrell** [comment]
Rebased on master (now using elli), still same problem.  Your help is appreciated.

**Comment by gbour** [comment]
Hi @mworrell, just a quick notice to let you now I did not forgot your PR.
I'm still struggling at finding what's wrong with the standalone tls test.

**Comment by mworrell** [comment]
Thanks! In a couple of weeks I will give it a try against a boulder on my LAN, see if debugging gets easier.

- Marc

**Comment by mworrell** [comment]
Canceling this pull request.

We are now working on a branch closer to the master version.

**Pull request closed without merging**
