### PR TITLE
[refactor] use elli http server in replacement of cowboy

### PR DESCRIPTION
**Pull request by gbour**
cowboy and shotgun hex packages are both incompatibles.
Using elli instead of cowboy allows to use hex-only dependencies, and so to generate a buildable hex package for letsencrypt-erlang

### CODE REVIEW

**Comment by yurrriq** [comment]
Why not try [`elli-2.0.1`](https://hex.pm/packages/elli/2.0.1)? :smile:

**Comment by deadtrickster** [comment]
and https://github.com/elli-lib/elli_prometheus too :-)

**Comment by gbour** [comment]
@yurrriq this branch was few month aged, I'll update to elli 2.0.1 in the next release :)
@deadtrickster I didn't know elli_prometheus. Can't it be installed & used in parallel of letsencrypt-erlang ?

**Comment by deadtrickster** [comment]
it has to be a part of middlewares stack

**Pull request merged**
